#!/bin/bash
7z a -r -t7z app.7z -mx -m0=BCJ2 -m1=LZMA:d24 -m2=LZMA:d19 -m3=LZMA:d19 -mb0:1 -mb0s1:2 -mb0s2:3
cp $HOME/scripts/.autorepack_files/* .
echo "copy /B 7zSD.Win32.sfx+app.tag+app.7z repack.exe" | wine cmd
